# Generated by Django 3.0.6 on 2020-05-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Replay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replay', models.FileField(upload_to='media/')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
