# Generated by Django 3.0.6 on 2020-05-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replay',
            name='replay',
            field=models.FileField(upload_to=''),
        ),
    ]
