# Generated by Django 3.0.6 on 2020-05-26 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('replays', '0002_auto_20200523_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='replay',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='replay',
            name='summoner',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='replay',
            name='title',
            field=models.CharField(blank=True, default='', max_length=75),
        ),
    ]
